### ISSUE TITLE
Pico-08 Native "Could Not Load Cart" on RG35XX OG

### ISSUE THREAD

**Issue by AronZero** [Turro75/MyMinUI#30]
Hi Turro75,

Native Pico-08 works really great on most of the Pico-08 I've played specially with the sound. However not all games are working and I want to have an idea as to why that happen since I expected that all games should run using the Native Pico-08. Here are the games I tried:

1. Astrox: Into the Cosmic Chaos - I personally made this game, it is a single cart shmup project. It only works on fake-08 but not with the Native one. when I run it it says "Could not load"
https://www.lexaloffle.com/bbs/?pid=149887#p

2. Kalikan - It loads but as soon as I pick a character it says "Download failed"
https://www.lexaloffle.com/bbs/?pid=131586#p

I hope you tried this on your end, not sure why some games still not working on the Native Pico-08.

Thank you!

**Comment by Turro75** [comment]
Astrox (nice game!) is working here, maybe You have to update your pico8 bin files or just a corrupted cart file?

Kalikan is not working offline, never found a way to get it running.

**Comment by AronZero** [comment]
Thank you Turro75! hope you enjoyed the game :). I still can't run my game, but I promise you it isn't corrupted. Not sure if you're referring to these bin files: _(see image below)_
![image](https://github.com/user-attachments/assets/189dc522-6246-461b-b262-e3b8f1641961)

I only did was to copy and paste the licensed "pico8.dat" and "pico_dyn" to the ff. folders:
1. \Tools\rg35xx\Pico-8 Splore.pak\pico8-native
2. \Bios\P8

As for Kalikan and similar games, I believe they will never run unless the device is linked to WiFi the first time you launch them; after that, they will work offline.

**Comment by ribolovac510** [comment]
Hi, I've tried running both of them and they work on my end too. I've only added the "pico8.dat" and "pico8_dyn" files to the P8 bios folder and the .p8.png carts to the Pico-8 Native (P8N) folder and everything was good to go.

Kalikan does indeed download cart files from the BBS when you load the levels and go back to the main menu. In order to play offline you need to put the downloaded .nfo and .p8.png files in the "Pico-8 Splore.pak\pico8-native\\.lexaloffle\pico-8\bbs\carts" folder after doing a run with both of the ships in the game either on your PC or some WiFi capable handheld.

![carts](https://github.com/user-attachments/assets/91dc8600-8728-4bd2-97ed-e4d876662e43)

On a side note, I've had some trouble running Virtua Racing Demake, it would get stuck while loading a stage, but I've managed to fix it by running it first through Splore. I've edited Splore's launch.sh to look for the Pico-8 Native (P8N) folder by editing the "romdir=" line. After running it once through Splore making sure to go into a stage, it would load correctly now by running it from Pico-8 Native directly. Not sure if that would help in your case, but give it a try if nothing else helps.

**Comment by AronZero** [comment]
Hi [ribolovac510](https://github.com/ribolovac510), you're a life saver! I can now play Kalikan.  For my game (Astrox), I remembered that I exported it using the most recent version of Pico-08 (v0.2.6b), despite the fact that my device is running a lesser version (v0.2.5g). What I did was copy the "pico8.dat" and "pico_dyn" files from the latest version to my device, and it now works.

Thanks for all of your help! Case closed 😎
